import Link from "next/link";
import { ArrowUpRight, ChevronRight, MapPin, MoveUpRight, ShieldCheck } from "lucide-react";
import { Logo } from "@/components/logo";
import { Reveal } from "@/components/reveal";

export default function HomePage() {
  return <main className="grain min-h-screen overflow-hidden">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-7 lg:px-10"><Logo /><div className="hidden items-center gap-8 text-xs font-semibold uppercase tracking-[.14em] text-ash md:flex"><Link href="#how-it-works" className="hover:text-charcoal">How it works</Link><Link href="#principles" className="hover:text-charcoal">Our promise</Link></div><Link href="/auth" className="group flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em]">Enter portal <ArrowUpRight size={16} className="transition group-hover:translate-x-1 group-hover:-translate-y-1" /></Link></nav>
    <section className="mx-auto grid max-w-7xl gap-12 px-6 pb-20 pt-14 lg:grid-cols-[1.08fr_.92fr] lg:px-10 lg:pb-32 lg:pt-20">
      <div className="relative z-10 flex flex-col justify-center"><Reveal><p className="eyebrow mb-7">Chennai · human-first mobility</p><h1 className="display max-w-3xl text-[clamp(4.2rem,9vw,8.5rem)] leading-[.84] tracking-[-.065em]">Every journey,<br /><span className="text-amber">beautifully</span><br />connected.</h1><p className="mt-10 max-w-md text-lg leading-8 text-ash">AERIDE gives the everyday ride a little more intention — considered routes, trusted people, and a calm way to move through the city.</p><div className="mt-10 flex flex-wrap items-center gap-4"><Link href="/auth?mode=register" className="inline-flex min-h-12 items-center gap-3 bg-charcoal px-6 text-xs font-bold uppercase tracking-[.14em] text-ivory transition hover:bg-amber hover:text-charcoal">Book your first ride <MoveUpRight size={16} /></Link><Link href="#how-it-works" className="inline-flex min-h-12 items-center gap-2 border-b border-charcoal text-xs font-bold uppercase tracking-[.14em]">See how it works <ChevronRight size={16} /></Link></div></Reveal></div>
      <div className="relative min-h-[480px] bg-[#e7e3d8] lg:min-h-[620px]"><div className="absolute inset-0 opacity-50" style={{ backgroundImage: "linear-gradient(30deg, transparent 48%, #c2bdb0 49%, transparent 50%), linear-gradient(120deg, transparent 48%, #c2bdb0 49%, transparent 50%)", backgroundSize: "84px 84px" }} /><div className="absolute left-[16%] top-[13%] h-[70%] w-[70%] rounded-[50%] border border-[#c5bca9]" /><div className="absolute left-[27%] top-[26%] h-[45%] w-[45%] rounded-[50%] border border-[#c5bca9]" /><svg className="absolute inset-0 h-full w-full" viewBox="0 0 500 620" fill="none" aria-label="Abstract route illustration"><path d="M80 480C132 418 120 330 224 345C307 358 282 235 383 166" stroke="#171717" strokeWidth="2" strokeDasharray="5 7" /><path d="M80 480C132 418 120 330 224 345C307 358 282 235 383 166" stroke="#D99A38" strokeWidth="5" strokeLinecap="round" strokeDasharray="1 11" /><circle cx="80" cy="480" r="8" fill="#171717" /><circle cx="383" cy="166" r="8" fill="#D99A38" /><circle cx="383" cy="166" r="16" stroke="#171717" /></svg><div className="absolute bottom-8 left-8 flex items-center gap-3 bg-charcoal px-4 py-3 text-ivory"><MapPin size={16} className="text-amber" /><span className="text-xs tracking-wide">A considered route through Chennai</span></div><span className="eyebrow absolute right-7 top-7 [writing-mode:vertical-rl]">Est. 2024 / AERIDE</span></div>
    </section>
    <section id="how-it-works" className="border-t border-line bg-[#1b1b19] px-6 py-20 text-ivory lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-8 border-b border-white/20 pb-12 md:flex-row"><div><p className="eyebrow text-[#b6b3ab]">The AERIDE rhythm</p><h2 className="display mt-5 max-w-xl text-5xl leading-none tracking-[-.04em] md:text-7xl">Move through<br />the noise <span className="text-amber">lightly.</span></h2></div><p className="max-w-xs self-end text-sm leading-7 text-[#b6b3ab]">The system is built around clear decisions: a fair quote, a verified driver, a visible trip, and a receipt that tells the whole story.</p></div><div className="grid gap-px bg-white/15 md:grid-cols-3">{[["01", "Choose your route", "Start with two places. Our distance-aware fare engine gives you a transparent quote before a driver is assigned."], ["02", "Meet the right driver", "Every driver and vehicle has a verification trail. Availability is managed transactionally, so no ride is double-booked."], ["03", "Arrive with a record", "Trip events, payments, and reviews stay connected. Your journey history is yours to return to." ]].map(([n, title, copy]) => <div key={n} className="bg-[#1b1b19] p-8 md:min-h-64"><p className="text-sm text-amber">{n}</p><h3 className="display mt-12 text-3xl">{title}</h3><p className="mt-4 text-sm leading-6 text-[#b6b3ab]">{copy}</p></div>)}</div></div></section>
    <section id="principles" className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-[.7fr_1.3fr] lg:px-10 lg:py-28"><div><p className="eyebrow">Built for trust</p><h2 className="display mt-5 text-5xl leading-none tracking-[-.04em]">The details<br />matter.</h2></div><div className="grid gap-8 md:grid-cols-2"><div className="border-t border-charcoal pt-5"><ShieldCheck size={20} /><h3 className="mt-10 text-lg font-semibold">Verified by design</h3><p className="mt-3 text-sm leading-6 text-ash">Document expiry, active status, and verification live close to the operational data — where they can be acted on.</p></div><div className="border-t border-charcoal pt-5"><span className="display text-4xl text-amber">₹</span><h3 className="mt-7 text-lg font-semibold">Decimal-safe fares</h3><p className="mt-3 text-sm leading-6 text-ash">Quotes are persisted with the trip, protecting the passenger’s history when policy rates change later.</p></div></div></section>
    <footer className="border-t border-line px-6 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-xs text-ash md:flex-row"><span>© 2026 AERIDE / DBMS academic system</span><span>Every journey, beautifully connected.</span></div></footer>
  </main>;
}
