"use client";
import { useState } from "react";
import { ArrowRight, Car, Check, CircleAlert } from "lucide-react";
import { Button } from "./button";
import { useRouter } from "next/navigation";

export function BookingForm() { const [form, setForm] = useState({ pickupLocation: "Chennai Central", dropLocation: "Tidel Park", vehicleType: "Sedan" }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ type: "ok" | "error"; text: string } | null>(null); const router = useRouter();
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(null); const res = await fetch("/api/trips", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const json = await res.json(); setBusy(false); if (!res.ok) return setMessage({ type: "error", text: json.error || "Booking failed." }); setMessage({ type: "ok", text: `Route ${json.trip.tripId} is in the system.` }); setTimeout(() => router.push("/dashboard/history"), 900); }
  return <form onSubmit={submit} className="space-y-7"><div><p className="eyebrow mb-5">1 / Your route</p><div className="space-y-3"><LocationField label="Pickup" value={form.pickupLocation} onChange={(v) => setForm({ ...form, pickupLocation: v })} /><LocationField label="Destination" value={form.dropLocation} onChange={(v) => setForm({ ...form, dropLocation: v })} /></div></div><div><p className="eyebrow mb-4">2 / Your vehicle</p><div className="grid gap-2 sm:grid-cols-3">{["Hatchback", "Sedan", "SUV"].map((type) => <button type="button" key={type} onClick={() => setForm({ ...form, vehicleType: type })} className={`flex flex-col items-start gap-3 border p-4 text-left transition ${form.vehicleType === type ? "border-charcoal bg-charcoal text-ivory" : "border-line hover:border-charcoal"}`}><Car size={18} className={form.vehicleType === type ? "text-amber" : "text-ash"} /><span className="text-sm font-semibold">{type}</span><span className={`text-[11px] ${form.vehicleType === type ? "text-[#aaa8a0]" : "text-ash"}`}>{type === "SUV" ? "Up to 6 seats" : "Up to 4 seats"}</span></button>)}</div></div>{message && <div className={`flex items-start gap-2 p-4 text-sm ${message.type === "ok" ? "bg-[#e3eee1] text-[#3e7040]" : "bg-[#f7e8e4] text-[#8b3528]"}`}>{message.type === "ok" ? <Check size={17} /> : <CircleAlert size={17} />}{message.text}</div>}<Button type="submit" disabled={busy} className="w-full">{busy ? "Finding your route..." : "Request ride"}<ArrowRight size={16} /></Button><p className="text-center text-[11px] leading-5 text-ash">Quote is calculated using the active fare policy and saved with this trip.</p></form>; }
function LocationField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block border border-line bg-ivory p-3"><span className="eyebrow block">{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full bg-transparent text-sm outline-none" required /></label>; }
