"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowUpRight, CarFront, Clock3, MapPin, Plus, Route, ShieldCheck } from "lucide-react";
import { Button } from "./button";
import { StatusPill } from "./status-pill";
import { money } from "@/lib/fare";

type Trip = { tripId: string; pickupLocation: string; dropLocation: string; status: string; distanceKm?: string; estimatedFare?: string; finalFare?: string; requestedAt?: string; assignments?: { driver: { firstName: string; lastName?: string | null; driverId: string } }[] };
export function DashboardClient({ role }: { role: string }) {
  const [data, setData] = useState<{ trips: Trip[]; total?: number; users?: number; drivers?: number; revenue?: string; active?: number; pendingDocs?: number; monthly?: { month: string; total: string }[] } | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/overview").then((r) => r.json()).then(setData).catch(() => setError("Could not load the workspace.")); }, []);
  const trips = data?.trips ?? [];
  if (role === "ADMIN") return <AdminHome data={data} />;
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-12 lg:py-12"><header className="flex flex-col justify-between gap-6 border-b border-line pb-8 md:flex-row md:items-end"><div><p className="eyebrow">{role === "DRIVER" ? "Driver workspace" : "Passenger workspace"}</p><h1 className="display mt-3 text-5xl tracking-[-.05em] md:text-6xl">Good morning<span className="text-amber">.</span></h1><p className="mt-3 text-sm text-ash">{role === "DRIVER" ? "Your next thoughtful drive starts here." : "Where would you like to go today?"}</p></div><Link href={role === "DRIVER" ? "/dashboard/history" : "/dashboard/book"}><Button><Plus size={16} />{role === "DRIVER" ? "View trip queue" : "Book a ride"}</Button></Link></header>{error && <p className="mt-6 border border-[#d8a49a] bg-[#f7e8e4] p-4 text-sm text-[#8b3528]">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-3"><Stat label="All trips" value={data?.total?.toString() ?? "—"} icon={<Route size={17} />} /><Stat label={role === "DRIVER" ? "Availability" : "In motion"} value={role === "DRIVER" ? "Ready" : trips.filter((t) => ["ASSIGNED", "ACCEPTED", "IN_PROGRESS"].includes(t.status)).length.toString()} icon={<Clock3 size={17} />} /><Stat label="Saved time" value="2.4h" icon={<CarFront size={17} />} /></div><section className="mt-10 grid gap-7 lg:grid-cols-[1.25fr_.75fr]"><div className="border border-line bg-[#fbfaf7]"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><p className="eyebrow">Recent movement</p><h2 className="display mt-1 text-2xl">Your trip ledger</h2></div><Link href="/dashboard/history" className="text-xs font-bold uppercase tracking-[.12em] text-ash hover:text-charcoal">View all <ArrowUpRight size={14} className="ml-1 inline" /></Link></div>{trips.length === 0 ? <Empty text="No trips yet. Your first route is a few clicks away." /> : <div>{trips.map((trip) => <TripRow key={trip.tripId} trip={trip} />)}</div>}</div><div className="bg-charcoal p-6 text-ivory"><p className="eyebrow text-[#aaa8a0]">AERIDE note</p><h2 className="display mt-16 text-4xl leading-[.95]">The city is<br /><span className="text-amber">closer</span> than it feels.</h2><p className="mt-6 text-sm leading-6 text-[#aaa8a0]">Each quote keeps the policy used at booking, so tomorrow’s rates never rewrite today’s journey.</p><Link href="/dashboard/book" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-amber">Start a route <ArrowUpRight size={15} /></Link></div></section></div>;
}
function AdminHome({ data }: { data: any }) { return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-12 lg:py-12"><header className="border-b border-line pb-8"><p className="eyebrow">Stewardship console</p><h1 className="display mt-3 text-5xl tracking-[-.05em]">The system, in view<span className="text-amber">.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-ash">A live operational pulse from PostgreSQL — the academic model and its physical extensions, without the fog.</p></header><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Passengers" value={data?.users?.toString() ?? "—"} /><Stat label="Drivers" value={data?.drivers?.toString() ?? "—"} /><Stat label="Trips" value={data?.trips?.toString() ?? "—"} /><Stat label="Paid revenue" value={data?.revenue ? `₹${Number(data.revenue).toLocaleString("en-IN")}` : "—"} /></div><div className="mt-10 grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div className="border border-line bg-[#fbfaf7] p-6"><div className="flex items-end justify-between"><div><p className="eyebrow">Operating pulse</p><h2 className="display mt-1 text-3xl">What needs a look</h2></div><Link href="/admin/explorer" className="text-xs font-bold uppercase tracking-[.12em] text-ash hover:text-charcoal">Open explorer <ArrowUpRight size={14} className="ml-1 inline" /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="bg-paper p-5"><p className="eyebrow">Active trips</p><p className="display mt-4 text-5xl">{data?.active ?? "—"}</p><p className="mt-2 text-xs text-ash">assigned, accepted, or in progress</p></div><div className="bg-[#f7e8e4] p-5"><p className="eyebrow text-[#8b3528]">Expiring docs</p><p className="display mt-4 text-5xl text-[#8b3528]">{data?.pendingDocs ?? "—"}</p><p className="mt-2 text-xs text-[#8b3528]">within the next 30 days</p></div></div></div><div className="bg-amber p-6"><p className="eyebrow">Data posture</p><div className="mt-10 flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center border border-charcoal"><ShieldCheck size={22} /></div><div><p className="font-semibold">Constraints are active</p><p className="mt-1 text-xs leading-5">FKs · checks · audit events</p></div></div><p className="mt-12 max-w-xs text-sm leading-6">Use DBMS Explorer to demonstrate the relational model, safe analytics queries, and live rows during your viva.</p></div></div></div>; }
function Stat({ label, value, icon }: { label: string; value: string; icon?: React.ReactNode }) { return <div className="border border-line bg-[#fbfaf7] p-5"><div className="flex items-center justify-between text-ash"><p className="eyebrow">{label}</p>{icon}</div><p className="display mt-5 text-4xl tracking-[-.04em]">{value}</p></div>; }
function TripRow({ trip }: { trip: Trip }) { return <div className="flex flex-col gap-4 border-b border-line px-5 py-5 last:border-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><div className="mt-1 flex flex-col items-center"><span className="h-2 w-2 rounded-full bg-charcoal" /><span className="my-1 h-5 border-l border-dashed border-ash" /><span className="h-2 w-2 rounded-full border-2 border-amber" /></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{trip.pickupLocation}</p><p className="mt-1 truncate text-sm text-ash">{trip.dropLocation}</p><p className="mt-2 text-[11px] text-ash">{trip.tripId} · {trip.distanceKm ?? "—"} km</p></div></div><div className="flex items-center justify-between gap-5 sm:justify-end"><StatusPill status={trip.status} /><span className="text-sm font-semibold">{money(trip.finalFare ?? trip.estimatedFare)}</span></div></div>; }
function Empty({ text }: { text: string }) { return <div className="px-5 py-14 text-center text-sm text-ash">{text}</div>; }
