"use client";

import { useState } from "react";
import { Check, CircleAlert, CreditCard, Play, RotateCcw, WalletCards } from "lucide-react";
import { Button } from "./button";

const nextAction: Record<string, { to: "ACCEPTED" | "IN_PROGRESS" | "COMPLETED"; label: string }> = { ASSIGNED: { to: "ACCEPTED", label: "Accept request" }, ACCEPTED: { to: "IN_PROGRESS", label: "Start trip" }, IN_PROGRESS: { to: "COMPLETED", label: "Mark complete" } };
type Payment = { paymentId: string; status: string; amount: string | number };

export function TripActions({ tripId, status, role, payments = [], onChanged }: { tripId: string; status: string; role: string; payments?: Payment[]; onChanged: () => void }) {
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [method, setMethod] = useState<"CARD" | "UPI" | "CASH">("CARD"); const action = nextAction[status]; const paid = payments.find((payment) => payment.status === "PAID");
  async function transition(to: string) { setBusy(true); setNotice(""); const response = await fetch(`/api/trips/${tripId}/transition`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ to }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setNotice(data.error || "Could not update trip."); setNotice(`Trip moved to ${to.replaceAll("_", " ")}.`); onChanged(); }
  async function pay() { setBusy(true); setNotice(""); const response = await fetch("/api/payments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tripId, method }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setNotice(data.error || "Payment failed."); setNotice("Payment recorded. Receipt is ready below."); onChanged(); }
  return <div className="mt-5 border-t border-line pt-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">{role === "DRIVER" && action && <Button onClick={() => transition(action.to)} disabled={busy}><Play size={14} />{busy ? "Updating..." : action.label}</Button>}{role === "PASSENGER" && ["REQUESTED", "ASSIGNED", "ACCEPTED", "IN_PROGRESS"].includes(status) && <Button variant="secondary" onClick={() => transition("CANCELLED")} disabled={busy}><RotateCcw size={14} />Cancel trip</Button>}{status === "COMPLETED" && role === "PASSENGER" && !paid && <div className="flex flex-wrap items-center gap-2"><span className="eyebrow mr-1">Settle</span>{(["CARD", "UPI", "CASH"] as const).map((item) => <button key={item} onClick={() => setMethod(item)} className={`border px-3 py-2 text-[10px] font-bold uppercase tracking-[.1em] ${method === item ? "border-charcoal bg-charcoal text-ivory" : "border-line text-ash"}`}>{item}</button>)}<Button onClick={pay} disabled={busy}><CreditCard size={14} />{busy ? "Recording..." : "Pay now"}</Button></div>}{paid && <a href={`/api/receipts/${paid.paymentId}`} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.11em] text-ash hover:text-charcoal"><WalletCards size={15} />Download receipt</a>}</div>{notice && <p className={`mt-3 flex items-center gap-2 text-xs ${notice.includes("Could") || notice.includes("failed") ? "text-[#9a3f2e]" : "text-[#3e7040]"}`}>{notice.includes("Could") || notice.includes("failed") ? <CircleAlert size={14} /> : <Check size={14} />}{notice}</p>}</div>;
}
