"use client";

import { useEffect, useState } from "react";
import { Database, Play, ShieldCheck } from "lucide-react";
import { Button } from "@/components/button";

const querySet = [
  ["passenger_history", "Passenger history", "SELECT u.user_id, t.trip_id, t.pickup_location, t.drop_location, t.status FROM app_user u JOIN trip t ON t.user_id = u.user_id ORDER BY t.requested_at DESC;"],
  ["driver_earnings", "Driver earnings", "SELECT d.driver_id, SUM(p.amount) AS earnings FROM driver d LEFT JOIN payment p ON p.driver_id = d.driver_id GROUP BY d.driver_id;"],
  ["monthly_totals", "Monthly totals", "SELECT strftime('%Y-%m', payment_date) AS month, SUM(amount) AS total FROM payment GROUP BY month;"],
  ["revenue_by_payment", "Revenue by payment", "SELECT payment_method, SUM(amount) AS revenue FROM payment WHERE status = 'PAID' GROUP BY payment_method;"],
  ["active_passengers", "Highly active passengers", "SELECT user_id, COUNT(*) AS trips FROM trip GROUP BY user_id ORDER BY trips DESC;"],
  ["expiring_documents", "Expiring documents", "SELECT * FROM vehicle_document WHERE date(expiry_date) <= date('now','+30 day');"],
  ["average_ratings", "Average ratings", "SELECT ROUND(AVG(rating), 2) AS average_rating, COUNT(*) AS reviews FROM review;"],
  ["cancellation_rates", "Cancellation rates", "SELECT COUNT(*) AS total, SUM(status = 'CANCELLED') AS cancelled FROM trip;"],
];

export default function SqlLabPage() { const [active, setActive] = useState(querySet[0][0]); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [running, setRunning] = useState(false); const [error, setError] = useState(""); const selected = querySet.find((query) => query[0] === active) ?? querySet[0]; async function run(key = active) { setRunning(true); setError(""); const response = await fetch(`/api/dbms/queries?key=${key}`); const data = await response.json(); setRunning(false); if (!response.ok) return setError(data.error || "Query failed."); setRows(data.rows || []); } useEffect(() => { run(); }, []); const columns = rows[0] ? Object.keys(rows[0]) : [];
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-12 lg:py-12"><header className="flex flex-col justify-between gap-6 border-b border-line pb-8 md:flex-row md:items-end"><div><p className="eyebrow">Admin-only / SQLite console</p><h1 className="display mt-3 text-5xl tracking-[-.05em]">SQL Query Lab<span className="text-amber">.</span></h1><p className="mt-3 max-w-xl text-sm leading-6 text-ash">Select an academic query, inspect the SQLite statement, and run it against live seeded data.</p></div><div className="flex items-center gap-2 text-xs text-[#3e7040]"><ShieldCheck size={15} /> Allow-listed queries only</div></header><div className="mt-8 grid gap-6 lg:grid-cols-[.36fr_1fr]"><aside className="border border-line bg-[#fbfaf7] p-4"><div className="mb-4 flex items-center gap-2 px-2"><Database size={16} /><p className="eyebrow">Query library</p></div><div className="space-y-1">{querySet.map(([key, label]) => <button key={key} onClick={() => { setActive(key); run(key); }} className={`w-full px-3 py-3 text-left text-xs font-bold ${active === key ? "bg-charcoal text-ivory" : "hover:bg-paper"}`}>{label}</button>)}</div></aside><section className="border border-line bg-[#fbfaf7] p-5 sm:p-7"><div className="flex flex-col justify-between gap-4 border-b border-line pb-6 sm:flex-row sm:items-center"><div><p className="eyebrow">{selected[1]}</p><pre className="mt-4 max-w-3xl whitespace-pre-wrap bg-[#20201e] p-4 text-xs leading-6 text-[#e7dfcd]">{selected[2]}</pre></div><Button onClick={() => run()} disabled={running}><Play size={14} />{running ? "Running" : "Run query"}</Button></div>{error && <p className="mt-6 bg-[#f7e8e4] p-4 text-sm text-[#8b3528]">{error}</p>}{!error && rows.length === 0 && <p className="py-16 text-center text-sm text-ash">{running ? "Reading SQLite rows..." : "No rows returned."}</p>}{rows.length > 0 && <div className="mt-6 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-charcoal">{columns.map((column) => <th key={column} className="px-3 py-3 uppercase tracking-[.11em]">{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-b border-line last:border-0">{columns.map((column) => <td key={column} className="whitespace-nowrap px-3 py-3 text-ash">{String(row[column] ?? "—")}</td>)}</tr>)}</tbody></table></div>}</section></div></div>;
}
